//
// Created by markf on 1/5/2026.
//

#ifndef LIBRARYDATABASEMANAGEMENT_SEARCHDATABASE_H
#define LIBRARYDATABASEMANAGEMENT_SEARCHDATABASE_H

void lookupEntry();
void viewAllEntries();

#endif //LIBRARYDATABASEMANAGEMENT_SEARCHDATABASE_H